apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
data:
  SPRING_DATASOURCE_URL: "<DB_URL>"
  SPRING_DATASOURCE_USERNAME: "<DB_USER>"
  MAIL_HOST: "localhost"
  MAIL_PORT: "25"
  MAIL_FROM: "noreply@oficina.local"
  SERVER_PORT: "8080"
