apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: <DB_PASS_B64>
  JWT_SECRET: <JWT_SECRET_B64>
  MAIL_USER: ""
  MAIL_PASS: ""
