name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: \${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: oficina-gke-cluster    
  GKE_ZONE: us-central1-a  
  IMAGE: oficina-api
  REGISTRY: us-central1-docker.pkg.dev/\${{ secrets.GCP_PROJECT_ID }}/oficina-repo

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '\${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Docker Auth
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |-
        docker build -t "$REGISTRY/$IMAGE:\${{ github.sha }}" -t "$REGISTRY/$IMAGE:latest" .
        docker push "$REGISTRY/$IMAGE:\${{ github.sha }}"
        docker push "$REGISTRY/$IMAGE:latest"

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: \${{ env.GKE_CLUSTER }}
        location: \${{ env.GKE_ZONE }}

    - name: Replace Secrets and Env Vars in K8s Manifests
      run: |-
        sed -i "s|ghcr.io/marinhomich/oficina-mecanica-api:latest|$REGISTRY/$IMAGE:\${{ github.sha }}|g" k8s/app.yaml
        sed -i "s|<DB_URL>|\${{ secrets.DB_URL }}|g" k8s/configmap.yaml
        sed -i "s|<DB_USER>|\${{ secrets.DB_USER }}|g" k8s/configmap.yaml
        sed -i "s|<DB_PASS_B64>|\${{ secrets.DB_PASS_B64 }}|g" k8s/secret.yaml
        sed -i "s|<JWT_SECRET_B64>|\${{ secrets.JWT_SECRET_B64 }}|g" k8s/secret.yaml

    - name: Deploy to GKE
      run: |-
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/app.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl rollout status deployment/oficina-api -n oficina
